version: "3"
services:
  wyl:
    image: renemanqueros/watchyourlan
    network_mode: "host"        
    restart: unless-stopped
    volumes:
    - ~/.dockerdata/wyl:/data
    environment:
      TZ: Asia/Novosibirsk              # required: needs your TZ for correct time
      IFACE: "virbr-bw wlxf4ec3892dd51" # required: 1 or more interface
      DBPATH: "/data/db.sqlite"         # optional, default: /data/db.sqlite
      GUIIP: "0.0.0.0"                  # optional, default: localhost
      GUIPORT: "8840"                   # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 60
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "darkly"                   # optional